// Spanish 15 vocabulary — extracted from the course Canvas modules.
// Item format: [spanish, english] or [spanish, english, hint]
window.SP15 = (() => {
const units = [];
const unit = (id, num, title, color) => { const u = {id, num, title, color, topics: []}; units.push(u); return u; };
const topic = (u, id, name, day, items, verbSets) => u.topics.push({id, name, day, items, verbSets: verbSets || []});

// ───────────────────────── Unit 1 ─────────────────────────
const u1 = unit("u1", "1", "Identity, home, and belonging", "#D60070");

topic(u1, "greetings", "Greetings and introductions", "Day 2", [
["hola", "hello, hi"],
["buenos días", "good morning"],
["buenas tardes", "good afternoon"],
["me llamo...", "my name is..."],
["mi nombre es...", "my name is..."],
["¿cómo te llamas?", "what's your name?"],
["¿cuál es tu nombre?", "what's your name?"],
["mi apellido es...", "my last name is..."],
["¿cuál es tu apellido?", "what's your last name?"],
["su nombre es...", "her/his name is..."],
["¿cuál es su nombre?", "what's her/his name?"],
["mucho gusto", "pleased to meet you"],
["igualmente", "likewise"],
["¿cómo estás?", "how are you?"],
["(muy) bien, ¿y tú?", "(very) well, and you?"],
["¿de dónde eres?", "where are you from?"],
["soy de...", "I am from..."],
["¿puedes repetir, por favor?", "could you repeat, please?"],
["disculpa, no entiendo", "I'm sorry, I don't understand"],
["gracias", "thank you"],
["de nada", "you're welcome"],
["por favor", "please"],
["no sé", "I don't know"],
["no recuerdo", "I don't remember"],
["¿cómo se deletrea...?", "how do you spell...?"],
["adiós", "goodbye"],
["hasta luego", "see you later"],
["nos vemos", "see you"],
["hasta pronto", "see you soon"],
["cuídate", "take care"],
["el saludo", "greeting"],
["la despedida", "goodbye, farewell"],
["el abrazo", "hug"],
["el beso", "kiss"],
["el apretón de manos", "handshake"],
]);

topic(u1, "nationalities", "Countries and nationalities", "Day 2", [
["argentino/a", "Argentine"],
["australiano/a", "Australian"],
["boliviano/a", "Bolivian"],
["brasileño/a", "Brazilian"],
["chileno/a", "Chilean"],
["chino/a", "Chinese"],
["colombiano/a", "Colombian"],
["cubano/a", "Cuban"],
["egipcio/a", "Egyptian"],
["filipino/a", "Filipino"],
["griego/a", "Greek"],
["indio/a", "Indian"],
["italiano/a", "Italian"],
["mexicano/a", "Mexican"],
["nigeriano/a", "Nigerian"],
["polaco/a", "Polish"],
["ruso/a", "Russian"],
["sueco/a", "Swedish"],
["turco/a", "Turkish"],
["venezolano/a", "Venezuelan"],
["alemán/alemana", "German"],
["danés/danesa", "Danish"],
["español/española", "Spanish"],
["francés/francesa", "French"],
["inglés/inglesa", "English"],
["portugués/portuguesa", "Portuguese"],
["belga", "Belgian"],
["croata", "Croatian"],
["canadiense", "Canadian"],
["costarricense", "Costa Rican"],
["estadounidense", "American (from the US)"],
["norteamericano/a", "(North) American"],
["marroquí", "Moroccan"],
["iraní", "Iranian"],
["paquistaní", "Pakistani"],
["Alemania", "Germany"],
["Bélgica", "Belgium"],
["Brasil", "Brazil"],
["Canadá", "Canada"],
["Dinamarca", "Denmark"],
["Egipto", "Egypt"],
["España", "Spain"],
["Estados Unidos", "United States"],
["Filipinas", "Philippines"],
["Francia", "France"],
["Grecia", "Greece"],
["Inglaterra", "England"],
["Marruecos", "Morocco"],
["Polonia", "Poland"],
["Suecia", "Sweden"],
["Turquía", "Turkey"],
["el país", "country"],
["la nacionalidad", "nationality"],
["¿de dónde es ella?", "where is she from?"],
["¿de dónde son ellos?", "where are they from?"],
]);

topic(u1, "pronouns", "Pronouns and the verb ser", "Day 2", [
["yo", "I"],
["tú", "you (informal)"],
["usted", "you (formal)"],
["él", "he"],
["ella", "she"],
["nosotros / nosotras", "we"],
["ustedes", "you (plural)"],
["ellos / ellas", "they"],
["vosotros", "you (plural, Spain)"],
["vos", "you (informal, Central America)"],
["ser", "to be (origin, traits, time, dates)"],
["soy de Venezuela", "I'm from Venezuela"],
["ustedes son graciosos", "you all are funny"],
["gracioso/a", "funny"],
], ["core"]);

topic(u1, "numbers", "Numbers 0–100", "Day 3", [
["cero", "0"], ["uno", "1"], ["dos", "2"], ["tres", "3"], ["cuatro", "4"], ["cinco", "5"],
["seis", "6"], ["siete", "7"], ["ocho", "8"], ["nueve", "9"], ["diez", "10"], ["once", "11"],
["doce", "12"], ["trece", "13"], ["catorce", "14"], ["quince", "15"], ["dieciséis", "16"],
["diecisiete", "17"], ["dieciocho", "18"], ["diecinueve", "19"], ["veinte", "20"],
["veintiuno", "21"], ["veintidós", "22"], ["veintitrés", "23"], ["veinticuatro", "24"],
["veinticinco", "25"], ["veintiséis", "26"], ["veintisiete", "27"], ["veintiocho", "28"],
["veintinueve", "29"], ["treinta", "30"], ["treinta y dos", "32"], ["cuarenta", "40"], ["cuarenta y seis", "46"],
["cincuenta", "50"], ["sesenta", "60"], ["setenta", "70"], ["ochenta", "80"], ["noventa", "90"],
["noventa y cuatro", "94"], ["cien", "100"],
["¿cuántos años tienes?", "how old are you?"],
["tengo veinte años", "I am twenty years old"],
]);

topic(u1, "articles", "Articles and agreement", "Day 3", [
["el", "the (masculine singular)"],
["la", "the (feminine singular)"],
["los", "the (masculine plural)"],
["las", "the (feminine plural)"],
["un", "a, an (masculine)"],
["una", "a, an (feminine)"],
["unos", "some (masculine)"],
["unas", "some (feminine)"],
["el libro", "book"],
["la casa", "house"],
["la silla", "chair"],
["el zapato", "shoe"],
["la gata", "female cat"],
["masculino", "masculine"],
["femenino", "feminine"],
["singular", "singular"],
["plural", "plural"],
]);

topic(u1, "personality", "Personality adjectives", "Day 3", [
["honesto/a", "honest"],
["imaginativo/a", "imaginative"],
["apasionado/a", "passionate"],
["extrovertido/a", "extroverted"],
["divertido/a", "fun"],
["serio/a", "serious"],
["aburrido/a", "boring (with ser)"],
["excéntrico/a", "eccentric"],
["cómico/a", "funny"],
["gracioso/a", "funny"],
["introvertido/a", "introverted"],
["simpático/a", "nice"],
["inteligente", "intelligent"],
["pesimista", "pessimistic"],
["alegre", "happy, cheerful"],
["fiel", "faithful, loyal"],
["egoísta", "selfish"],
["liberal", "liberal"],
["agradable", "agreeable, pleasant"],
["sociable", "sociable"],
["la personalidad", "personality"],
]);

topic(u1, "physical", "Physical descriptions", "Day 3", [
["alto/a", "tall"],
["bajo/a", "short (height)"],
["rubio/a", "blond"],
["moreno/a", "dark-haired, dark-skinned"],
["castaño/a", "brown-haired"],
["pelirrojo/a", "red-haired"],
["blanco/a", "white"],
["negro/a", "black"],
["afrolatino/a", "Afro-Latino"],
["flaco/a", "skinny"],
["delgado/a", "thin"],
["gordo/a", "fat"],
["joven", "young"],
["viejo/a", "old"],
["mayor", "older, elderly"],
["calvo/a", "bald"],
["guapo/a", "good-looking"],
["feo/a", "ugly"],
["el pelo", "hair"],
["el pelo rizado", "curly hair"],
["el pelo ondulado", "wavy hair"],
["el pelo liso", "straight hair"],
["el pelo recogido", "hair tied up"],
["el pelo suelto", "hair down, loose"],
["el pelo canoso", "gray hair"],
["el pelo teñido", "dyed hair"],
["el pelo corto", "short hair"],
["el pelo largo", "long hair"],
["los ojos", "eyes"],
["los ojos marrones", "brown eyes"],
["los ojos verdes", "green eyes"],
["los ojos azules", "blue eyes"],
["los ojos negros", "dark eyes"],
["la nariz", "nose"],
["grande", "big"],
["pequeño/a", "small"],
["la barba", "beard"],
["el bigote", "mustache"],
["la perilla", "goatee"],
["las gafas", "glasses"],
["las pecas", "freckles"],
["un lunar", "a mole, beauty mark"],
["los labios pintados", "lipstick (painted lips)"],
["la coleta", "ponytail"],
["las trenzas", "braids"],
["los pendientes", "earrings"],
["el collar", "necklace"],
["los accesorios", "accessories"],
["llevar", "to wear, to have on"],
["tener el pelo liso", "to have straight hair"],
["tener los ojos marrones", "to have brown eyes"],
]);

topic(u1, "tener", "Tener and its expressions", "Day 4", [
["tener", "to have"],
["tener ... años", "to be ... years old"],
["tener que + verbo", "to have to (do something)"],
["tengo que hacer la tarea", "I have to do the homework"],
["tener hambre", "to be hungry"],
["tener sed", "to be thirsty"],
["tener frío", "to be cold"],
["tener calor", "to be hot"],
["tener miedo", "to be afraid"],
["la tarea", "homework"],
["la manzana", "apple"],
["el carro", "car"],
["el tomate", "tomato"],
["el infinitivo", "infinitive"],
["hablar", "to speak, to talk"],
["comer", "to eat"],
["vivir", "to live"],
], ["core"]);

topic(u1, "dates", "Months, days, and dates", "Day 4", [
["enero", "January"], ["febrero", "February"], ["marzo", "March"], ["abril", "April"],
["mayo", "May"], ["junio", "June"], ["julio", "July"], ["agosto", "August"],
["septiembre", "September"], ["octubre", "October"], ["noviembre", "November"], ["diciembre", "December"],
["lunes", "Monday"], ["martes", "Tuesday"], ["miércoles", "Wednesday"], ["jueves", "Thursday"],
["viernes", "Friday"], ["sábado", "Saturday"], ["domingo", "Sunday"],
["el mes", "month"], ["la semana", "week"], ["el día", "day"],
["los días de la semana", "the days of the week"],
["la fecha", "date"],
["el cumpleaños", "birthday"],
["¿cuándo es tu cumpleaños?", "when is your birthday?"],
["el doce de febrero", "February 12th"],
["¿cuándo?", "when?"],
["los lunes tengo clase de español", "on Mondays I have Spanish class"],
]);

topic(u1, "verbs1", "Everyday verbs (gustar + infinitive)", "Days 4 and 6", [
["gustar", "to like (to be pleasing to)"],
["me gusta", "I like"],
["te gusta", "you like"],
["le gusta", "he/she likes"],
["nos gusta", "we like"],
["les gusta", "they / you all like"],
["me gusta correr", "I like running"],
["comer", "to eat"],
["caminar", "to walk"],
["comprar", "to buy"],
["escuchar", "to listen to"],
["jugar", "to play (a game or sport)"],
["ir", "to go"],
["correr", "to run"],
["dormir", "to sleep"],
["trabajar", "to work"],
["ver", "to see, to watch"],
["hacer", "to do, to make"],
["hacer ejercicio", "to exercise"],
["beber", "to drink"],
["leer", "to read"],
["estudiar", "to study"],
["manejar / conducir", "to drive"],
["buscar", "to look for"],
["escribir", "to write"],
["hablar", "to speak, to talk"],
["tocar (un instrumento)", "to play (an instrument)"],
["aprender", "to learn"],
["cocinar", "to cook"],
["necesitar", "to need"],
["ver televisión", "to watch TV"],
]);

topic(u1, "family", "Family", "Day 5", [
["la familia", "family"],
["el abuelo", "grandfather"],
["la abuela", "grandmother"],
["el padre / el papá", "father, dad"],
["la madre / la mamá", "mother, mom"],
["los padres", "parents"],
["el hijo", "son"],
["la hija", "daughter"],
["los hijos", "children (sons and daughters)"],
["el hermano", "brother"],
["la hermana", "sister"],
["el tío", "uncle"],
["la tía", "aunt"],
["el primo", "cousin (male)"],
["la prima", "cousin (female)"],
["el cuñado", "brother-in-law"],
["la cuñada", "sister-in-law"],
["la nuera", "daughter-in-law"],
["el yerno", "son-in-law"],
["el sobrino", "nephew"],
["la sobrina", "niece"],
["el nieto", "grandson"],
["la nieta", "granddaughter"],
["el matrimonio", "marriage"],
["el parentesco", "kinship, family relationship"],
["tradicional", "traditional"],
["¿cómo es tu familia?", "what is your family like?"],
]);

topic(u1, "possessives", "Hay and possessive adjectives", "Day 5", [
["hay", "there is, there are"],
["hay una silla", "there is one chair"],
["hay dos sillas", "there are two chairs"],
["mi / mis", "my"],
["tu / tus", "your (informal)"],
["su / sus", "his, her, your (formal), their"],
["nuestro / nuestra", "our"],
["nuestros / nuestras", "our (plural)"],
["mi hermano", "my brother"],
["su abuela", "his/her grandmother"],
["sus tíos", "his/her uncles"],
["nuestras primas", "our cousins"],
["el lápiz", "pencil"],
["la mochila", "backpack"],
["la mosca", "fly (insect)"],
["la comida", "food"],
["el restaurante", "restaurant"],
["muchos libros", "many books"],
["buenas ideas", "good ideas"],
]);

topic(u1, "ir", "Ir and future plans", "Day 6", [
["ir", "to go"],
["ir a + infinitivo", "to be going to (do something)"],
["voy a viajar a Perú", "I'm going to travel to Peru"],
["viajar", "to travel"],
["enseñar", "to teach"],
["pasear al perro", "to walk the dog"],
["el perro", "dog"],
["el supermercado", "supermarket"],
["el parque", "park"],
["el campus", "campus"],
["todos los días", "every day"],
["cuatro veces por semana", "four times a week"],
["por las mañanas", "in the mornings"],
["mañana", "tomorrow"],
["esta semana", "this week"],
["la próxima semana", "next week"],
["el próximo mes", "next month"],
["después de clase", "after class"],
["el futuro", "the future"],
], ["core"]);

topic(u1, "clothing", "Clothing", "Day 7", [
["la ropa", "clothing, clothes"],
["la prenda", "garment, piece of clothing"],
["usar / llevar", "to wear"],
["una camiseta", "T-shirt"],
["una camiseta de tirantes", "tank top"],
["una camiseta de mangas cortas", "short-sleeved T-shirt"],
["una camiseta polo", "polo shirt"],
["una sudadera", "sweatshirt, hoodie"],
["una camisa", "shirt (button-up)"],
["un vestido", "dress"],
["unos pantalones", "pants"],
["unos pantalones vaqueros", "jeans"],
["los jeans / los vaqueros", "jeans"],
["unos pantalones cortos", "shorts"],
["una falda", "skirt"],
["una blusa", "blouse"],
["un jersey", "sweater"],
["un traje", "suit"],
["unas bragas", "panties"],
["un sujetador", "bra"],
["unos calzoncillos", "underwear, boxers"],
["unos calcetines", "socks"],
["un albornoz", "bathrobe"],
["unas pantuflas", "slippers"],
["un pijama", "pajamas"],
["un abrigo", "coat"],
["una bufanda", "scarf"],
["unos guantes", "gloves"],
["un gorro", "beanie, knit hat"],
["una gabardina", "trench coat, raincoat"],
["una chaqueta", "jacket"],
["un bañador", "swimsuit"],
["un biquini", "bikini"],
["unas gafas de sol", "sunglasses"],
["unas gafas", "glasses"],
["una gorra", "cap"],
["un sombrero", "hat"],
["unos zapatos", "shoes"],
["unos zapatos de tacón", "high heels"],
["unas botas", "boots"],
["unas zapatillas", "sneakers"],
["unas zapatillas de deporte", "sports sneakers, trainers"],
["los tenis", "sneakers"],
["unas sandalias", "sandals"],
["una corbata", "tie"],
["una pajarita", "bow tie"],
["un cinturón", "belt"],
["un bolso", "handbag, purse"],
["una cartera", "wallet"],
["cómodo/a", "comfortable"],
["elegante", "elegant"],
["formal", "formal"],
["informal", "informal, casual"],
["práctico/a", "practical"],
["ligero/a", "light (weight)"],
["la playa", "beach"],
["la boda", "wedding"],
["el estado de ánimo", "mood"],
["los colores", "colors"],
]);

topic(u1, "estar", "Estar: feelings and places", "Day 7", [
["estar", "to be (location, temporary states)"],
["feliz", "happy"],
["triste", "sad"],
["cansado/a", "tired"],
["relajado/a", "relaxed"],
["tranquilo/a", "calm"],
["estar aburrido/a", "to be bored"],
["ser aburrido/a", "to be boring"],
["estar en casa", "to be at home"],
["¿estás en tu casa?", "are you home?"],
["delante de", "in front of"],
["detrás de", "behind"],
["junto a", "next to"],
["entre", "between"],
["en frente de", "in front of, across from"],
["a la derecha de", "to the right of"],
["a la izquierda de", "to the left of"],
["Boylston Hall está detrás de Widener", "Boylston Hall is behind Widener"],
["las emociones", "emotions"],
["permanente", "permanent"],
["temporal", "temporary"],
], ["core"]);

topic(u1, "subjects", "Classes and subjects", "Day 8", [
["la asignatura", "course, subject"],
["la clase", "class"],
["la historia", "history"],
["la química", "chemistry"],
["la biología", "biology"],
["la estadística", "statistics"],
["la lengua", "language"],
["el laboratorio de química", "chemistry lab"],
["el seminario de primer año", "freshman seminar"],
["la economía", "economics"],
["la filosofía", "philosophy"],
["las matemáticas", "mathematics"],
["la psicología", "psychology"],
["la música", "music"],
["la religión", "religion"],
["la física", "physics"],
["la computación", "computer science"],
["la programación", "programming"],
["la carrera", "degree program, major"],
["el grado / la licenciatura", "bachelor's degree"],
["el posgrado", "graduate studies"],
["el Derecho", "law (field of study)"],
["la Medicina", "medicine (field of study)"],
["el sistema educativo", "educational system"],
]);

topic(u1, "time", "Telling time", "Day 8", [
["¿qué hora es?", "what time is it?"],
["es la una", "it's one o'clock"],
["son las tres", "it's three o'clock"],
["en punto", "o'clock, sharp"],
["y cinco", "five past"],
["y cuarto", "quarter past"],
["y media", "half past"],
["un cuarto para las cuatro", "quarter to four"],
["cinco para las cuatro", "five to four"],
["la una menos diez", "ten to one"],
["de la mañana", "in the morning (a.m.)"],
["de la tarde", "in the afternoon (p.m.)"],
["de la noche", "at night (p.m.)"],
["a las nueve", "at nine (o'clock)"],
["la clase empieza a las nueve", "class starts at nine"],
["la hora", "hour, time"],
["el horario", "schedule"],
["¿a qué hora?", "at what time?"],
]);

topic(u1, "campus", "Campus and classroom", "Day 9", [
["la universidad", "university"],
["el edificio", "building"],
["la biblioteca", "library"],
["la librería", "bookstore"],
["la casa", "house"],
["el dormitorio", "dorm, bedroom"],
["el comedor", "dining hall, dining room"],
["el gimnasio", "gym"],
["el aula", "classroom"],
["la pizarra", "board, whiteboard"],
["la silla", "chair"],
["la mesa", "table"],
["el escritorio", "desk"],
["la mochila", "backpack"],
["el libro", "book"],
["la computadora", "computer"],
["el bolígrafo", "pen"],
["el cuaderno", "notebook"],
["el lápiz", "pencil"],
["el laboratorio", "lab"],
["el / la estudiante", "student"],
["el profesor / la profesora", "professor"],
["famoso/a", "famous"],
["grande", "big, large"],
["cerca de", "near"],
["la mayoría", "the majority, most"],
["hacer ejercicio", "to exercise"],
["visitar", "to visit"],
["el segundo año", "sophomore year"],
]);

topic(u1, "regular", "Regular verbs in the present", "Day 9", [
["necesitar", "to need"],
["trabajar", "to work"],
["hablar", "to talk, to speak"],
["desayunar", "to have breakfast"],
["estudiar", "to study"],
["enseñar", "to teach"],
["llamar", "to call"],
["almorzar", "to have lunch"],
["practicar", "to practice"],
["tocar", "to play (an instrument), to touch"],
["caminar", "to walk"],
["cenar", "to have dinner"],
["comer", "to eat"],
["correr", "to run"],
["asistir (a)", "to attend"],
["abrir", "to open"],
["beber", "to drink"],
["aprender", "to learn"],
["escribir", "to write"],
["subir", "to go up"],
["leer", "to read"],
["ver", "to see"],
["vivir", "to live"],
["decidir", "to decide"],
["la rutina", "routine"],
["todas las mañanas", "every morning"],
], ["regular"]);

topic(u1, "city", "The city", "Day 10", [
["la ciudad", "city"],
["las afueras", "outskirts, suburbs"],
["el centro", "downtown"],
["el barrio", "neighborhood"],
["la parada de autobús", "bus stop"],
["la estación de metro", "subway station"],
["la estación de tren", "train station"],
["el aeropuerto", "airport"],
["el cine", "movie theater"],
["la casa", "house"],
["el apartamento", "apartment"],
["la escuela", "school"],
["el parque", "park"],
["el supermercado", "supermarket"],
["el mercado", "market"],
["el bar", "bar"],
["la iglesia", "church"],
["la calle", "street"],
["el tráfico", "traffic"],
["el carro", "car"],
["la tienda", "store"],
["el edificio", "building"],
["la gente", "people"],
["el lugar", "place"],
["el transporte público", "public transportation"],
["el metro", "subway"],
["el río", "river"],
["el camino", "path, way, trail"],
["el / la turista", "tourist"],
["el / la residente", "resident"],
["histórico/a", "historic"],
["único/a", "unique"],
["reconocido/a", "well-known, renowned"],
["descansar", "to rest"],
["fundado/a", "founded"],
["el nordeste", "northeast"],
]);

topic(u1, "weather", "Weather and seasons", "Day 11", [
["el clima", "climate"],
["el tiempo", "weather"],
["¿cómo es el clima?", "what's the climate like?"],
["¿cómo está el tiempo hoy?", "what's the weather like today?"],
["seco/a", "dry"],
["caliente / caluroso/a", "hot"],
["húmedo/a", "humid"],
["templado/a", "mild, temperate"],
["agradable", "pleasant"],
["tropical", "tropical"],
["fresco/a", "cool"],
["soleado/a", "sunny"],
["nublado/a", "cloudy"],
["tormentoso/a", "stormy"],
["lleno de niebla", "foggy"],
["ventoso/a", "windy"],
["lluvioso/a", "rainy"],
["helado/a", "icy"],
["el sol", "sun"],
["el viento", "wind"],
["el calor", "heat"],
["el frío", "cold"],
["la nube", "cloud"],
["la niebla", "fog"],
["el hielo", "ice"],
["la lluvia", "rain"],
["la llovizna", "drizzle, light shower"],
["el aguacero", "downpour"],
["la humedad", "humidity"],
["la temperatura", "temperature"],
["el trueno", "thunder"],
["la tormenta", "storm"],
["la tormenta de truenos", "thunderstorm"],
["la brisa", "breeze"],
["el granizo", "hail"],
["la nieve", "snow"],
["hace sol", "it's sunny"],
["está nublado", "it's cloudy"],
["llueve", "it's raining"],
["nieva", "it's snowing"],
["hace calor", "it's hot"],
["hace buena temperatura", "it's warm (nice temperature)"],
["hace fresco", "it's cool"],
["hace frío", "it's cold"],
["está lloviendo muchísimo", "it's pouring"],
["las estaciones", "seasons"],
["el invierno", "winter"],
["la primavera", "spring"],
["el verano", "summer"],
["el otoño", "fall, autumn"],
["la temperatura máxima", "high temperature"],
["la temperatura mínima", "low temperature"],
["sorprendente", "surprising"],
]);

topic(u1, "comparisons", "Comparisons", "Day 11", [
["más ... que", "more ... than"],
["menos ... que", "less ... than"],
["tan ... como", "as ... as"],
["tanto/a ... como", "as much ... as"],
["tantos/as ... como", "as many ... as"],
["mejor", "better"],
["peor", "worse"],
["más frío que", "colder than"],
["frecuentemente", "frequently"],
["lentamente", "slowly"],
["rápidamente", "quickly"],
["la contaminación", "pollution"],
["hermoso/a", "beautiful"],
["gastar", "to spend"],
["el dinero", "money"],
["subir", "to rise, to go up"],
["Bogotá tiene menos estaciones que Boston", "Bogotá has fewer seasons than Boston"],
["Boston tiene tanta nieve como Nueva York", "Boston has as much snow as New York"],
]);

topic(u1, "house", "Parts of the house", "Day 12", [
["la casa", "house"],
["las partes de la casa", "parts of the house"],
["la cocina", "kitchen"],
["el salón", "living room"],
["el comedor", "dining room"],
["la habitación", "room, bedroom"],
["la habitación del niño", "child's room"],
["la entrada", "entrance, hall"],
["el baño", "bathroom"],
["el estudio", "study, home office"],
["el dormitorio", "bedroom"],
["el trastero", "storage room"],
["la vivienda", "housing"],
]);

topic(u1, "numbers100", "Numbers 100 and up", "Day 12", [
["cien", "100"],
["ciento uno", "101"],
["ciento treinta y cuatro", "134"],
["doscientos", "200"],
["trescientos", "300"],
["cuatrocientos", "400"],
["cuatrocientos cinco", "405"],
["quinientos", "500"],
["seiscientos", "600"],
["setecientos", "700"],
["ochocientos", "800"],
["novecientos", "900"],
["mil", "1,000"],
["dos mil", "2,000"],
["mil ochocientos noventa y siete", "1,897"],
["un millón", "1,000,000"],
["dos millones", "2,000,000"],
]);

topic(u1, "irregularyo", "Irregular yo forms, saber and conocer", "Day 12", [
["conocer", "to know (people, places), to be familiar with"],
["saber", "to know (facts, how to do something)"],
["dar", "to give"],
["hacer", "to do, to make"],
["poner", "to put"],
["salir", "to go out, to leave"],
["traer", "to bring"],
["ver", "to see"],
["conozco", "I know (a person or place)"],
["sé", "I know (a fact)"],
["doy", "I give"],
["hago", "I do, I make"],
["pongo", "I put"],
["salgo", "I go out"],
["traigo", "I bring"],
["veo", "I see"],
["irregular", "irregular"],
["memorizar", "to memorize"],
], ["yoirreg"]);

// ───────────────────────── Unit 2 ─────────────────────────
const u2 = unit("u2", "2", "Hispanos: participación y representación", "#0E4F9E");

topic(u2, "museums", "Museums and art", "Day 2", [
["el museo", "museum"],
["el arte moderno", "modern art"],
["el arte contemporáneo", "contemporary art"],
["el / la arquitecto/a", "architect"],
["la arquitectura", "architecture"],
["diseñar", "to design"],
["la forma", "shape, form"],
["la exposición", "exhibition"],
["el / la artista", "artist"],
["el símbolo", "symbol"],
["la pintura", "painting"],
["la escultura", "sculpture"],
["la obra", "work (of art)"],
["la pieza", "piece"],
["la colección", "collection"],
["el período", "period"],
["está prohibido", "it is forbidden"],
["tomar fotos", "to take photos"],
["visitado/a", "visited"],
["los pueblos indígenas", "Indigenous peoples"],
["la diversidad", "diversity"],
["el centro histórico", "historic center"],
["la entrada", "admission, entrance"],
["gratuito/a", "free of charge"],
["reconocido/a", "renowned, well-known"],
["el norte", "north"],
["presentar", "to present"],
["relevante", "relevant, important"],
["¿qué hacen los visitantes?", "what do the visitors do?"],
]);

topic(u2, "stem", "Stem-changing verbs", "Day 2", [
["soñar", "to dream"],
["costar", "to cost"],
["almorzar", "to have lunch"],
["dormir", "to sleep"],
["morir", "to die"],
["probar", "to taste, to try"],
["resolver", "to solve"],
["vestir", "to dress"],
["decir", "to say, to tell"],
["repetir", "to repeat"],
["jugar", "to play"],
["cerrar", "to close"],
["defender", "to defend"],
["entender", "to understand"],
["negar", "to deny"],
["preferir", "to prefer"],
["comenzar", "to begin"],
["empezar", "to begin"],
["divertir", "to amuse"],
["herir", "to hurt"],
["pensar", "to think"],
["querer", "to want"],
["confesar", "to confess"],
["mentir", "to lie"],
["perder", "to lose"],
["sugerir", "to suggest"],
["la raíz", "stem, root"],
["la terminación", "ending"],
["la sílaba", "syllable"],
], ["stem"]);

topic(u2, "routines", "Daily routines and reflexive verbs", "Day 3", [
["acostarse", "to go to bed"],
["cepillarse", "to brush (hair, teeth)"],
["cepillarse los dientes", "to brush one's teeth"],
["ducharse", "to take a shower"],
["quitarse", "to take off (clothing)"],
["peinarse", "to comb, to brush one's hair"],
["afeitarse", "to shave"],
["despertarse", "to wake up"],
["levantarse", "to get up"],
["ponerse", "to put on (clothing)"],
["vestirse", "to get dressed"],
["bañarse", "to bathe, to shower"],
["dormirse", "to fall asleep"],
["maquillarse", "to put on makeup"],
["lavarse", "to wash oneself"],
["lavarse las manos", "to wash one's hands"],
["lavarse el pelo", "to wash one's hair"],
["secarse", "to dry off"],
["prepararse", "to get ready"],
["verse", "to see oneself"],
["mirarse en el espejo", "to look at oneself in the mirror"],
["relajarse", "to relax"],
["regresar a casa", "to return home"],
["los dientes", "teeth"],
["las manos", "hands"],
["la cara", "face"],
["el espejo", "mirror"],
["los lentes", "glasses"],
["temprano", "early"],
["tarde", "late"],
["sin prisas", "without rushing"],
["primero", "first"],
["después", "afterwards, then"],
["antes de", "before"],
["mientras", "while"],
["entonces", "then, so"],
["a veces", "sometimes"],
["casi siempre", "almost always"],
["normalmente", "normally"],
["por la noche", "at night"],
["el / la abogado/a", "lawyer"],
["estresante", "stressful"],
["interesante", "interesting"],
["la rutina diaria", "daily routine"],
], ["reflexive"]);

topic(u2, "identity", "Hispano, latino, and identity", "Days 4–5", [
["hispano/a", "Hispanic"],
["latino/a", "Latino/a"],
["¿es lo mismo?", "is it the same?"],
["el gobierno", "government"],
["definir", "to define"],
["la cultura", "culture"],
["el origen", "origin"],
["la raza", "race"],
["el término", "term"],
["la década", "decade"],
["el censo", "census"],
["la minoría", "minority"],
["la población", "population"],
["la herencia cultural", "cultural heritage"],
["ofensivo/a", "offensive"],
["el colonizador", "colonizer"],
["inclusivo/a", "inclusive"],
["en la actualidad", "nowadays, currently"],
["los medios de comunicación", "the media"],
["la identidad", "identity"],
["el estereotipo", "stereotype"],
["la comunidad", "community"],
["los ancestros", "ancestors"],
["la profesión", "profession"],
["¿cuál es su profesión?", "what is his/her profession?"],
["¿por qué es famoso/a?", "why is he/she famous?"],
["sin embargo", "however"],
["por ejemplo", "for example"],
["añadir", "to add"],
["utilizar", "to use"],
["pertenecer", "to belong"],
]);

topic(u2, "progressive", "Present progressive", "Days 4–5", [
["estar + gerundio", "to be + -ing (present progressive)"],
["el gerundio", "gerund, present participle"],
["-ando", "-ing (for -ar verbs)"],
["-iendo", "-ing (for -er and -ir verbs)"],
["estudiando", "studying"],
["comprendiendo", "understanding"],
["escribiendo", "writing"],
["están estudiando español", "they are studying Spanish"],
["comprender", "to understand"],
["la carta de recomendación", "letter of recommendation"],
["la explicación", "explanation"],
["la gramática", "grammar"],
["ahora", "now"],
["¿qué está pasando?", "what's going on?"],
], ["gerund"]);

topic(u2, "porpara", "Por, para, and getting around", "Day 11", [
["para", "for, to, in order to (purpose, recipient, deadline)"],
["por", "for, by, through (cause, duration, route)"],
["la finalidad / el propósito", "purpose"],
["el destinatario", "recipient"],
["la fecha límite", "deadline"],
["la causa", "cause"],
["la duración", "duration"],
["la ruta", "route"],
["para ir a la escuela", "in order to go to school"],
["es para mi hermana", "it's for my sister"],
["para mí", "for me, in my opinion"],
["es para mañana", "it's due tomorrow"],
["por treinta minutos", "for thirty minutes"],
["por un año", "for a year"],
["diseñado por", "designed by"],
["caminar por la ciudad", "to walk through the city"],
["por la frontera sur", "via the southern border"],
["por persona", "per person"],
["reconocido/a por", "known for"],
["motivado/a por", "motivated by"],
["la bicicleta", "bicycle"],
["el boleto", "ticket"],
["el mapa", "map"],
["el tren", "train"],
["viajar en tren", "to travel by train"],
["el metro", "subway"],
["el automóvil", "automobile, car"],
["el transporte público", "public transportation"],
["caro/a", "expensive"],
["la megaciudad", "megacity"],
["construido/a", "built"],
["la frontera", "border"],
["pasar por", "to go through, to pass by"],
["llegar", "to arrive"],
]);

// ───────────────────────── Unit 3 ─────────────────────────
const u3 = unit("u3", "3", "Spanish in the United States", "#1B7F4F");

topic(u3, "song", "Somos más americanos (song)", "Day 1", [
["gritar", "to shout"],
["mil veces", "a thousand times"],
["regresar", "to return, to go back"],
["la tierra", "land, homeland"],
["aquí no quepo yo", "I don't fit (belong) here"],
["recordar", "to remind, to remember"],
["el gringo", "gringo (Anglo-American)"],
["cruzar", "to cross"],
["la frontera", "border"],
["nacer", "to be born"],
["libre", "free"],
["dividir", "to divide"],
["pintar la raya", "to paint the line"],
["brincar", "to jump"],
["el invasor", "invader"],
["el error", "mistake, error"],
["quitar", "to take away"],
["el estado", "state"],
["el extranjero", "foreigner"],
["la guerra", "war"],
["trabajador/a", "hard-working; worker"],
["mentir", "to lie"],
["la historia", "history"],
["la gloria", "glory"],
["poderoso/a", "powerful"],
["la nación", "nation"],
["el guerrero", "warrior"],
["valiente", "brave"],
["el indio", "Indigenous person"],
["el continente", "continent"],
["mezclado/a", "mixed"],
["el siglo", "century"],
["anglosajón", "Anglo-Saxon"],
["las aguas del río", "the waters of the river"],
["arrebatar", "to snatch away"],
["la sangre", "blood"],
["mestizo/a", "mestizo, of mixed heritage"],
["de todos colores", "of every color"],
["el oficio", "trade, occupation"],
["contar", "to count, to tell"],
["aunque le duela", "even if it hurts"],
["el vecino", "neighbor"],
["yo no crucé la frontera, la frontera me cruzó", "I didn't cross the border, the border crossed me"],
]);

topic(u3, "dop", "Direct object pronouns", "Day 1", [
["me", "me"],
["te", "you (direct object)"],
["lo", "him, it (masculine)"],
["la", "her, it (feminine)"],
["nos", "us"],
["los", "them (masculine)"],
["las", "them (feminine)"],
["Luis la tiene", "Luis has it (the class)"],
["prefiero tomarlas", "I prefer to take them"],
["las prefiero tomar", "I prefer to take them"],
["el objeto directo", "direct object"],
["el sujeto", "subject"],
["poder", "to be able to, can"],
["querer", "to want"],
["preferir", "to prefer"],
["necesitar", "to need"],
["tomar clases", "to take classes"],
["creativo/a", "creative"],
["la ciencia", "science"],
]);

topic(u3, "activists", "Dolores Huerta and Sonia Sotomayor", "Days 4 and 6", [
["nacer", "to be born"],
["nació en 1930", "she was born in 1930"],
["formar", "to form"],
["el sindicato", "labor union"],
["usar", "to use"],
["la frase", "phrase"],
["la campaña electoral", "electoral campaign"],
["¡Sí se puede!", "Yes we can!"],
["el / la activista", "activist"],
["los derechos", "rights"],
["la lucha", "fight, struggle"],
["el / la juez/a", "judge"],
["la Corte Suprema", "Supreme Court"],
["la primera opción", "the first choice"],
["la decisión", "decision"],
["difícil", "difficult"],
["fácil", "easy"],
["inspirador/a", "inspiring"],
["la carrera", "career"],
["las leyes", "law (the field)"],
["morir", "to die"],
["cumplir 9 años", "to turn 9 years old"],
["criar", "to raise (children)"],
["la niñez", "childhood"],
["la convicción", "conviction"],
["el camino", "path, road"],
["crecer", "to grow up"],
["el sueño", "dream"],
["humilde", "humble"],
["lograr", "to achieve"],
["conseguir", "to get, to achieve"],
["estudiar duro", "to study hard"],
["terminar", "to finish"],
["convertirse en", "to become"],
["el récord", "record"],
["la más joven", "the youngest"],
["nombrar", "to appoint, to name"],
["el expresidente", "former president"],
["la semana pasada", "last week"],
["dos veces", "twice"],
["el pasado", "the past"],
], ["pretreg", "pretirr"]);

topic(u3, "negatives", "Indefinite and negative words", "Day 5", [
["algo", "something"],
["alguien", "someone"],
["algún / alguna", "some, any"],
["algunos / algunas", "some"],
["también", "also, too"],
["nada", "nothing"],
["nadie", "no one, nobody"],
["ningún / ninguna", "not any"],
["ninguno / ninguna", "none"],
["tampoco", "neither, not either"],
["ni... ni...", "neither... nor..."],
["hay alguien en la puerta", "there is someone at the door"],
["no hay nadie en la puerta", "there is no one at the door"],
["tengo algo en el zapato", "I have something in my shoe"],
["no tengo nada en el zapato", "I don't have anything in my shoe"],
["la puerta", "door"],
["el zapato", "shoe"],
["la doble negación", "double negation"],
]);

topic(u3, "catlett", "Elizabeth Catlett (reading)", "Day 5", [
["de aquí y de allá", "from here and from there"],
["exiliarse", "to go into exile"],
["el tema", "theme, topic"],
["político/a", "political"],
["el arte", "art"],
["esclavizado/a", "enslaved"],
["la influencia", "influence"],
["profundo/a", "deep, profound"],
["rechazar", "to reject"],
["la admisión", "admission"],
["graduarse", "to graduate"],
["obtener", "to obtain, to get"],
["el máster", "master's degree"],
["centrarse en", "to focus on"],
["la mujer", "woman"],
["el muralismo", "muralism"],
["establecerse", "to settle"],
["desarrollar", "to develop"],
["unirse a", "to join"],
["el taller", "workshop"],
["el colectivo", "collective"],
["producir", "to produce"],
["accesible", "accessible"],
["el público", "the public"],
["crear", "to create"],
["representar", "to represent"],
["la figura", "figure"],
["llegar a ser", "to become"],
["el puesto", "position, post"],
["la ciudadanía", "citizenship"],
["mientras que", "whereas, while"],
["los vínculos", "ties, links"],
["la huelga", "strike (labor)"],
["recuperar", "to recover, to regain"],
["la muerte", "death"],
["yo veo", "I see"],
["yo pienso", "I think"],
["yo me pregunto", "I wonder"],
]);

// ───────────────────────── Verb conjugation sets ─────────────────────────
// Persons: yo, tú, ella/él/usted, nosotros, ellos/ustedes
// Entry: {inf, en, sc (stem change), yo (irregular yo form), forms (fully irregular), refl (reflexive)}
const verbSets = {
  core: { name: "Ser, estar, tener, ir", tense: "present", verbs: [
    {inf: "ser", en: "to be", forms: ["soy", "eres", "es", "somos", "son"]},
    {inf: "estar", en: "to be", forms: ["estoy", "estás", "está", "estamos", "están"]},
    {inf: "tener", en: "to have", forms: ["tengo", "tienes", "tiene", "tenemos", "tienen"]},
    {inf: "ir", en: "to go", forms: ["voy", "vas", "va", "vamos", "van"]},
  ]},
  regular: { name: "Regular verbs (present)", tense: "present", verbs: [
    "hablar:to speak", "comer:to eat", "vivir:to live", "necesitar:to need", "trabajar:to work",
    "desayunar:to have breakfast", "estudiar:to study", "enseñar:to teach", "llamar:to call",
    "practicar:to practice", "caminar:to walk", "cenar:to have dinner", "correr:to run",
    "asistir:to attend", "abrir:to open", "beber:to drink", "aprender:to learn", "escribir:to write",
    "subir:to go up", "leer:to read", "decidir:to decide", "cocinar:to cook", "escuchar:to listen to",
    "comprar:to buy", "buscar:to look for", "viajar:to travel",
  ].map(s => { const [inf, en] = s.split(":"); return {inf, en}; })},
  yoirreg: { name: "Irregular yo forms (present)", tense: "present", verbs: [
    {inf: "conocer", en: "to know (people, places)", yo: "conozco"},
    {inf: "dar", en: "to give", yo: "doy"},
    {inf: "hacer", en: "to do, to make", yo: "hago"},
    {inf: "poner", en: "to put", yo: "pongo"},
    {inf: "saber", en: "to know (facts)", yo: "sé"},
    {inf: "salir", en: "to go out", yo: "salgo"},
    {inf: "traer", en: "to bring", yo: "traigo"},
    {inf: "ver", en: "to see", yo: "veo"},
  ]},
  stem: { name: "Stem-changing verbs (present)", tense: "present", verbs: [
    {inf: "soñar", en: "to dream", sc: "o>ue"}, {inf: "costar", en: "to cost", sc: "o>ue"},
    {inf: "almorzar", en: "to have lunch", sc: "o>ue"}, {inf: "dormir", en: "to sleep", sc: "o>ue"},
    {inf: "morir", en: "to die", sc: "o>ue"}, {inf: "probar", en: "to taste, to try", sc: "o>ue"},
    {inf: "resolver", en: "to solve", sc: "o>ue"},
    {inf: "vestir", en: "to dress", sc: "e>i"}, {inf: "decir", en: "to say", sc: "e>i", yo: "digo"},
    {inf: "repetir", en: "to repeat", sc: "e>i"},
    {inf: "jugar", en: "to play", sc: "u>ue"},
    {inf: "cerrar", en: "to close", sc: "e>ie"}, {inf: "defender", en: "to defend", sc: "e>ie"},
    {inf: "entender", en: "to understand", sc: "e>ie"}, {inf: "negar", en: "to deny", sc: "e>ie"},
    {inf: "preferir", en: "to prefer", sc: "e>ie"}, {inf: "comenzar", en: "to begin", sc: "e>ie"},
    {inf: "empezar", en: "to begin", sc: "e>ie"}, {inf: "divertir", en: "to amuse", sc: "e>ie"},
    {inf: "herir", en: "to hurt", sc: "e>ie"}, {inf: "pensar", en: "to think", sc: "e>ie"},
    {inf: "querer", en: "to want", sc: "e>ie"}, {inf: "confesar", en: "to confess", sc: "e>ie"},
    {inf: "mentir", en: "to lie", sc: "e>ie"}, {inf: "perder", en: "to lose", sc: "e>ie"},
    {inf: "sugerir", en: "to suggest", sc: "e>ie"},
  ]},
  reflexive: { name: "Reflexive verbs (present)", tense: "present", verbs: [
    {inf: "acostarse", en: "to go to bed", refl: true, sc: "o>ue"},
    {inf: "cepillarse", en: "to brush", refl: true},
    {inf: "ducharse", en: "to take a shower", refl: true},
    {inf: "quitarse", en: "to take off", refl: true},
    {inf: "peinarse", en: "to comb one's hair", refl: true},
    {inf: "afeitarse", en: "to shave", refl: true},
    {inf: "despertarse", en: "to wake up", refl: true, sc: "e>ie"},
    {inf: "levantarse", en: "to get up", refl: true},
    {inf: "ponerse", en: "to put on", refl: true, yo: "pongo"},
    {inf: "vestirse", en: "to get dressed", refl: true, sc: "e>i"},
    {inf: "bañarse", en: "to bathe", refl: true},
    {inf: "dormirse", en: "to fall asleep", refl: true, sc: "o>ue"},
    {inf: "maquillarse", en: "to put on makeup", refl: true},
    {inf: "lavarse", en: "to wash oneself", refl: true},
    {inf: "verse", en: "to see oneself", refl: true, yo: "veo"},
    {inf: "relajarse", en: "to relax", refl: true},
    {inf: "secarse", en: "to dry off", refl: true},
  ]},
  gerund: { name: "Present progressive (gerunds)", tense: "gerund", verbs: [
    {inf: "estudiar", en: "to study"}, {inf: "comprender", en: "to understand"}, {inf: "escribir", en: "to write"},
    {inf: "hablar", en: "to speak"}, {inf: "comer", en: "to eat"}, {inf: "vivir", en: "to live"},
    {inf: "trabajar", en: "to work"}, {inf: "aprender", en: "to learn"}, {inf: "correr", en: "to run"},
    {inf: "beber", en: "to drink"}, {inf: "hacer", en: "to do"}, {inf: "ver", en: "to see"},
    {inf: "leer", en: "to read", ger: "leyendo"},
    {inf: "dormir", en: "to sleep", ger: "durmiendo"}, {inf: "morir", en: "to die", ger: "muriendo"},
    {inf: "vestir", en: "to dress", ger: "vistiendo"}, {inf: "decir", en: "to say", ger: "diciendo"},
    {inf: "repetir", en: "to repeat", ger: "repitiendo"}, {inf: "preferir", en: "to prefer", ger: "prefiriendo"},
    {inf: "mentir", en: "to lie", ger: "mintiendo"}, {inf: "sugerir", en: "to suggest", ger: "sugiriendo"},
    {inf: "divertir", en: "to amuse", ger: "divirtiendo"}, {inf: "herir", en: "to hurt", ger: "hiriendo"},
  ]},
  pretreg: { name: "Regular verbs (preterite)", tense: "preterite", verbs: [
    "hablar:to speak", "trabajar:to work", "estudiar:to study", "formar:to form", "usar:to use",
    "terminar:to finish", "comer:to eat", "vivir:to live", "desayunar:to have breakfast",
    "consumir:to consume", "nacer:to be born", "aprender:to learn", "escribir:to write",
    "decidir:to decide", "viajar:to travel", "visitar:to visit", "cumplir:to turn (an age)",
    "crecer:to grow up", "lograr:to achieve", "recibir:to receive",
  ].map(s => { const [inf, en] = s.split(":"); return {inf, en}; })},
  pretirr: { name: "Irregular verbs (preterite)", tense: "preterite", verbs: [
    {inf: "estar", en: "to be", forms: ["estuve", "estuviste", "estuvo", "estuvimos", "estuvieron"]},
    {inf: "ir", en: "to go", forms: ["fui", "fuiste", "fue", "fuimos", "fueron"]},
    {inf: "ser", en: "to be", forms: ["fui", "fuiste", "fue", "fuimos", "fueron"]},
    {inf: "hacer", en: "to do, to make", forms: ["hice", "hiciste", "hizo", "hicimos", "hicieron"]},
    {inf: "dar", en: "to give", forms: ["di", "diste", "dio", "dimos", "dieron"]},
    {inf: "ver", en: "to see", forms: ["vi", "viste", "vio", "vimos", "vieron"]},
    {inf: "decir", en: "to say", forms: ["dije", "dijiste", "dijo", "dijimos", "dijeron"]},
    {inf: "traer", en: "to bring", forms: ["traje", "trajiste", "trajo", "trajimos", "trajeron"]},
    {inf: "poder", en: "to be able to", forms: ["pude", "pudiste", "pudo", "pudimos", "pudieron"]},
    {inf: "poner", en: "to put", forms: ["puse", "pusiste", "puso", "pusimos", "pusieron"]},
    {inf: "querer", en: "to want", forms: ["quise", "quisiste", "quiso", "quisimos", "quisieron"]},
  ]},
};

return { units, verbSets };
})();
